- name: ensure nginx is at the latest version
  apt:
    name: nginx
    state: latest
    update_cache: yes
    cache_valid_time: 3600

#- name: mod systemctl nginx
#  template:
#    src: files/nginx/nginx.service
#    dest: /lib/systemd/system/nginx.service
#    owner: root
#    group: root
#    mode: 0644
#    force: yes
#  notify:
#    - systemctl daemon-reload
#
#- name: write the nginx config file
#  template:
#    src: templates/nginx/nginx.conf.j2
#    dest: /etc/nginx/nginx.conf
#    owner: root
#    group: root
#    mode: 0664
#  notify:
#    - restart nginx
#
#- name: delete nginx conf default symlink
#  file: path="/etc/nginx/sites-enabled/default" state=absent
#
#- name: create nginx conf symlink
#  file:
#    path: "/etc/nginx/sites-enabled/{{ service_name }}"
#    src: "/etc/nginx/sites-available/{{ service_name }}"
#    owner: root
#    group: root
#    mode: 0777
#    state: link
#    force: yes
#
#- name: write the nginx config file -application-
#  template:
#    src: templates/nginx/{{ rails_layer_name }}_{{ service_name }}.j2
#    dest: /etc/nginx/sites-available/{{ service_name }}
#    owner: root
#    group: root
#    mode: 0644
#  notify:
#  - restart nginx
#
#- name: start nginx
#  service:
#    name: nginx
#    enabled: yes
