- name: create user
  user:
    name: "{{user.name}}"
    shell: /bin/bash
    createhome: yes

- name: mkdir .ssh
  file: dest=/home/{{user.name}}/.ssh state=directory owner={{user.name}} group={{user.name}} mode=700

- name: check public key exist
  stat:
    path: /usr/local/src/pubkeys/{{user.name}}.pub
  register: public_key

- name: copy publickey
  copy: src=/usr/local/src/pubkeys/{{user.name}}.pub dest=/home/{{user.name}}/.ssh/authorized_keys owner={{user.name}} group={{user.name}} mode=600
  when: public_key.stat.exists == true

- name: set visudo
  lineinfile:
    dest: /etc/sudoers
    backup: yes
    line: "{{user.name}} ALL=(ALL) NOPASSWD: ALL"
  when: user.sudo == 'yes'
