- debug: var=ansible_date_time
- name: set system timezone to Asia/Tokyo
  timezone:
    name: Asia/Tokyo
  tags:
    set-timezone

# Todo: python3で影響を受ける
- name: set selinux to permissive
  selinux:
    policy: targeted
    state: disabled
  tags:
    disable-selinux

- name: modify sudoers 1/2
  lineinfile:
    path: /etc/sudoers
    backup: yes
    regexp: '^Defaults.*\!visiblepw$'
    line: 'Defaults   visiblepw'
  tags:
    modify-sudoers

- name: modify sudoers 2/2
  lineinfile:
    path: /etc/sudoers
    backup: yes
    regexp: '^%wheel\s'
    line: '%wheel        ALL=(ALL)       NOPASSWD: ALL'
  tags:
    modify-sudoers

- name: create /etc/skel/.ssh
  file:
    path: /etc/skel/.ssh
    state: directory
    owner: root
    group: root
    mode: 0700
  tags:
    config-skel

- name: create /etc/skel/.ssh/authorized_keys
  file:
    path: /etc/skel/.ssh/authorized_keys
    state: touch
    owner: root
    group: root
    mode: 0600
  tags:
    config-skel

- name: install remi repository
  yum:
    name: http://rpms.famillecollet.com/enterprise/remi-release-7.rpm
    state: present
  tags:
    install-repository

- name: install utilities
  yum:
    name:
      - git
      - zip
      - unzip
      - mariadb
      - wget
      - sysstat
      - python-requests
      - python36
    state: latest
  tags:
    install-utilities

- name: install cloud_sql_proxy module
  get_url:
    url: https://dl.google.com/cloudsql/cloud_sql_proxy.linux.amd64
    dest: /usr/local/bin/cloud_sql_proxy
    force: yes
    mode: 0755
  tags:
    install-cloud-sql-proxy-module

- name: get monitoring tool google-cloud-ops-agent installer
  get_url:
    url: https://dl.google.com/cloudagents/add-google-cloud-ops-agent-repo.sh
    dest: /root/add-google-cloud-ops-agent-repo.sh
    force: yes
    mode: 0755
  tags:
    install-monitoring-tool

- name: install monitoring tool google-cloud-ops-agent
  shell:
    bash /root/add-google-cloud-ops-agent-repo.sh --also-install
  tags:
    install-monitoring-tool

- name: change parmission /var/log/messages
  file:
    path: /var/log/messages
    owner: root
    group: root
    mode: 0644
  tags:
    config-syslog
